#Deploy storage class of type gp2
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: gp2-sc
  awsElasticBlockStore:
    volumeID: vol-0610ebf5178675a4e

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-data
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi