apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: cm9vdA==
  password: cHc=
  key_id: QVNJQVlSUFVMRzdJNjJaVktKNzU=
  access_key: NzVrd3hvZFJaKzJ0TWx5eXRTdm50M1pUQTJjaEtBU09BdTZpNmlyZw==
  session_token: RndvR1pYSXZZWGR6RVAvLy8vLy8vLy8vL3dFYURLa2xLRWhjUVRwMUlMQlVEeUxKQWZQS1FvVEErMUlza0xLZXdtZWgzQzRiVC9LU015eFV3V0tKbTRuWlQ4Sm1IRGw3WVZzTjN1YU9aUnF3dGRNUWRmT1U4Q3VOZlRLbGhOQ2EzWkwvTVdlMngvakVtRmNuZVhSUHRENHNCL21laU94RHB2ZVFEL0k0YjVaU0l1NmF5UTVZbjhrMS9ZdU5yZnBNakJCWjQzZ3BFVUxOL2hKSm1LaS9QaVZKa3VZaEZYdGNpNk54MjFyU0ZadTgyUmtJYTJ4TFM4aGRud0Vid09ESU1PbXVhWWN4TFRvcFM4Y0dkcUh1Tm45allnSnpqUE1mR1p6NmNOdVhFTC9DOHRKTXhIZXZRNGIzOEZRVW1paVIvTitoQmpJdG84Vi95UGVCNzJQOTFXcEdwcWVsb1FaVkhXdWEza3lvV2VLcktOOG9Gc3BTVml5STZMWU83dlpnSFc0OQ==