#Deploy storage class of type gp2
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2-sc
spec: 
  accessModes:
  - ReadWriteOnce
  resources: 
    requests:
      storage: 2Gi
  volumeMode: Filesystem